# .github/workflows/my-workflow.yml
name: Website - Production
on:
  push:
    branches:
      - main 
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/main
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v1
        with:
          path: themes/my-theme/src/node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - run: make deps
      - run: make lint
      - run: make build
        env:
          NODE_ENV: production

      - shell: 'bash'
        run: |-
          echo '${{ secrets.GCP_SA_KEY }}' | wc -c

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - id: 'upload-files'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'dist'
          destination: 'michael-com'
          parent: false
          predefinedAcl: publicRead
          headers: |-
            Cache-Control: public, max-age=3600

      