# .github/workflows/my-workflow.yml
name: Website - Production
on:
  push:
    branches:
      - main 
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v1
        with:
          path: themes/my-theme/src/node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - run: make deps
      - run: make lint
      - run: make build
        env:
          NODE_ENV: production
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'     
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
      - name: 'Set up GCloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      
      - run: gsutil -m rsync -d -c -r dist gs://michael-com
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://my-gcs-bucket/**/*.html
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://my-gcs-bucket/js/*.js
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://my-gcs-bucket/css/*.css

      