# .github/workflows/my-workflow.yml
name: Website - Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/main
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - run: make deps
      - run: make build
        env:
          NODE_ENV: production

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - id: "upload-files"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "public"
          destination: "michael-com"
          parent: false
          headers: |-
            Cache-Control: public, max-age=3600

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - id: "invalidation"
        run: 'gcloud compute url-maps invalidate-cdn-cache lb-michael-com --path "/*" --async'
